# PENDING MIGRATION - written, not yet applied
#
# This file is not part of the package namespace. It is installed under
# inst/migrations/ so that what is done to the database stays readable.
# See README.md in this directory.
#
#   source(system.file("migrations", "rename_data_d_to_date_d.R", package = "CafriplotsR"))
#   con <- CafriplotsR::call.mydb()
#   migrate_data_d_to_date_d(con)                   # rehearsal: prints, changes nothing
#   migrate_data_d_to_date_d(con, dry_run = FALSE)  # apply


#' Migration: rename data_liste_plots.data_d to date_d
#'
#' The day-of-survey column has been called `data_d` since the database was
#' built, alongside `date_y` and `date_m`. It is a typo, and it has quietly
#' split the codebase in two: the import templates generated by
#' `import_templates.R` hand users a `date_d` column, the validation rules in
#' `import_column_mapping.R` are keyed on `date_d`, and
#' `openforis_new_plot_processing.R` produces `date_d` - while the database,
#' the synonym table, the column descriptions and `get_table_columns()` all say
#' `data_d`. A day that crosses from one side to the other has no home.
#'
#' @details
#' Renaming is preferable to adding `date_d` as an alias: two columns for one
#' value is how the split becomes permanent.
#'
#' A rename is cheap - PostgreSQL rewrites no rows and updates dependent views,
#' indexes and constraints automatically, since they reference the column by
#' internal number rather than by name. What it is not is backward compatible.
#'
#' @section Apply this together with the matching code:
#' Every reference to `data_d` in the package is renamed in the same commit as
#' this file. Applying the migration without deploying that code, or deploying
#' that code without applying the migration, breaks the plot import path and
#' the census-information module, which queries the column by name in raw SQL
#' (`R/mod_census_information.R`). There is no transition window where both
#' spellings work.
#'
#' @section Scope:
#' `data_liste_plots` and any `followup_updates_*` audit mirror carrying the
#' same column - leaving a mirror as `data_d` would break the backup insert in
#' `backup_direct_records()`, which copies by column name. If any *other* table
#' has a `data_d` column, the migration reports it and refuses rather than
#' guessing whether it means the same thing.
#'
#' @param con Database connection with rights to ALTER these tables.
#' @param dry_run If TRUE (the default), run every check and report what would
#'   happen without altering anything.
#' @return Invisibly, a list with the tables in scope and their pre- and
#'   post-migration non-null counts.
#'
#' @examples
#' \dontrun{
#' con <- call.mydb()
#' migrate_data_d_to_date_d(con)                  # checks only
#' migrate_data_d_to_date_d(con, dry_run = FALSE) # apply
#' }
#'
#' @keywords internal
migrate_data_d_to_date_d <- function(con, dry_run = TRUE) {

  cli::cli_h1("Migration: data_liste_plots.data_d to date_d")

  if (!DBI::dbIsValid(con)) {
    cli::cli_abort("Invalid database connection")
  }

  # -- Step 1: where does data_d exist? -------------------------------------
  cli::cli_h2("Step 1: Tables carrying a data_d column")

  found <- DBI::dbGetQuery(con, "
    SELECT table_name, data_type
      FROM information_schema.columns
     WHERE table_schema = 'public'
       AND column_name = 'data_d'
     ORDER BY table_name")

  if (nrow(found) == 0) {
    cli::cli_alert_success("No data_d column anywhere - migration already applied")
    return(invisible(NULL))
  }
  print(found)

  in_scope <- found$table_name[
    found$table_name == "data_liste_plots" |
      grepl("^followup_updates_", found$table_name)
  ]
  out_of_scope <- setdiff(found$table_name, in_scope)

  if (length(out_of_scope) > 0) {
    cli::cli_abort(c(
      "Unexpected table{?s} carrying data_d: {.field {out_of_scope}}",
      i = "This migration only knows about data_liste_plots and its audit mirrors.",
      i = "Decide what those columns mean before renaming anything."
    ))
  }
  if (!"data_liste_plots" %in% in_scope) {
    cli::cli_abort("data_liste_plots has no data_d column - nothing to rename")
  }
  cli::cli_alert_info("In scope: {.field {in_scope}}")

  # -- Step 2: refuse to collide with an existing date_d ---------------------
  cli::cli_h2("Step 2: Checking date_d is free on those tables")

  clash <- DBI::dbGetQuery(con, glue::glue_sql("
    SELECT table_name
      FROM information_schema.columns
     WHERE table_schema = 'public'
       AND column_name = 'date_d'
       AND table_name IN ({in_scope*})", in_scope = in_scope, .con = con))

  if (nrow(clash) > 0) {
    cli::cli_abort(c(
      "{.field {clash$table_name}} already ha{?s/ve} a date_d column.",
      i = "Renaming would collide. Reconcile the two columns first."
    ))
  }
  cli::cli_alert_success("date_d is free on every table in scope")

  # -- Step 3: what depends on the column ------------------------------------
  cli::cli_h2("Step 3: Views referencing the column")

  views <- DBI::dbGetQuery(con, "
    SELECT DISTINCT view_schema, view_name
      FROM information_schema.view_column_usage
     WHERE table_name = 'data_liste_plots'
       AND column_name = 'data_d'")

  if (nrow(views) > 0) {
    print(views)
    cli::cli_alert_info(paste(
      "PostgreSQL tracks these by column number, so the rename follows through",
      "automatically. Listed so the change is not a surprise."
    ))
  } else {
    cli::cli_alert_success("No view references data_d")
  }

  # -- Step 4: how much data is at stake -------------------------------------
  cli::cli_h2("Step 4: Current contents")

  counts <- function(tbl) {
    DBI::dbGetQuery(con, sprintf(
      "SELECT count(*) AS n_rows, count(data_d) AS n_days FROM %s",
      DBI::dbQuoteIdentifier(con, tbl)))
  }
  before <- stats::setNames(lapply(in_scope, counts), in_scope)
  for (tbl in in_scope) {
    cli::cli_alert_info(
      "{tbl}: {before[[tbl]]$n_rows} row{?s}, {before[[tbl]]$n_days} with a day recorded"
    )
  }

  # -- Step 5: the change ----------------------------------------------------
  cli::cli_h2("Step 5: Renaming")

  statements <- sprintf(
    "ALTER TABLE %s RENAME COLUMN data_d TO date_d",
    vapply(in_scope, function(t) as.character(DBI::dbQuoteIdentifier(con, t)),
           character(1))
  )

  if (dry_run) {
    for (s in statements) cli::cli_alert_info("Would execute: {.code {s}}")
    cli::cli_alert_warning(paste(
      "Dry run - nothing was altered. Re-run with {.code dry_run = FALSE},",
      "and deploy the matching package code at the same time: there is no",
      "version that accepts both spellings."
    ))
    return(invisible(list(tables = in_scope, before = before, after = NULL)))
  }

  # Fail fast rather than queue behind a long query holding the table
  DBI::dbExecute(con, "SET lock_timeout = '30s'")

  DBI::dbBegin(con)
  ok <- tryCatch({
    for (s in statements) {
      cli::cli_alert_info("Executing: {.code {s}}")
      DBI::dbExecute(con, s)
    }
    DBI::dbCommit(con)
    TRUE
  }, error = function(e) {
    try(DBI::dbRollback(con), silent = TRUE)
    cli::cli_alert_danger("Migration rolled back: {e$message}")
    FALSE
  })
  if (!ok) stop("Migration failed - no change was committed.", call. = FALSE)

  # -- Step 6: confirm nothing moved -----------------------------------------
  cli::cli_h2("Step 6: Verifying the result")

  after_counts <- function(tbl) {
    DBI::dbGetQuery(con, sprintf(
      "SELECT count(*) AS n_rows, count(date_d) AS n_days FROM %s",
      DBI::dbQuoteIdentifier(con, tbl)))
  }
  after <- stats::setNames(lapply(in_scope, after_counts), in_scope)

  for (tbl in in_scope) {
    same <- identical(before[[tbl]]$n_rows, after[[tbl]]$n_rows) &&
      identical(before[[tbl]]$n_days, after[[tbl]]$n_days)
    if (same) {
      cli::cli_alert_success("{tbl}: {after[[tbl]]$n_days} day value{?s} carried over unchanged")
    } else {
      cli::cli_alert_danger(
        "{tbl}: counts changed ({before[[tbl]]$n_days} -> {after[[tbl]]$n_days}) - investigate"
      )
    }
  }

  leftover <- DBI::dbGetQuery(con, "
    SELECT table_name FROM information_schema.columns
     WHERE table_schema = 'public' AND column_name = 'data_d'")
  if (nrow(leftover) == 0) {
    cli::cli_alert_success("No data_d column remains")
  } else {
    cli::cli_alert_warning("data_d still present on: {leftover$table_name}")
  }

  cli::cli_alert_success("Migration complete")
  invisible(list(tables = in_scope, before = before, after = after))
}
